### ISSUE TITLE
knobs don't update

### ISSUE THREAD

**Issue by anishagg17** [uber/react-view#40]
related to #19 

I am using this configuration 

```
import * as React from "react";
import { EuiPopover, EuiButton } from "@elastic/eui";

export default () => {
  const [isOpen, setIsOpen] = React.useState(true);
  return (
    <EuiPopover
      isOpen={isOpen}
      anchorPosition="downCenter"
      panelPaddingSize="m"
      display="inlineBlock"
      button={
        <EuiButton
          iconType="arrowDown"
          iconSide="right"
          onClick={() => setIsOpen(!isOpen)}
        >
          Show popover
        </EuiButton>
      }
    >
      <div style={{ width: "300px" }}>
        Popover content that’s wider than the default
        width
      </div>
    </EuiPopover>
  );
}
```

state of `isOpen` prop is controlled by `EuiButton` but it does update the rendered component but the state of toggle remains the same. Also there are no code changes within the editor.

![Hnet com-image (2)](https://user-images.githubusercontent.com/43617894/84423999-0e3bbd00-ac3d-11ea-9920-937bb03a5991.gif)

**Comment by tajo** [comment]
Can you share the props configuration?

**Comment by anishagg17** [comment]
```
const props = {
  isOpen: {
    type: PropTypes.Boolean,
    value: false,
    stateful: true,
  },
  button: {
    type: PropTypes.ReactNode,
    value: `<EuiButton
      iconType="arrowDown"
      iconSide="right"
      onClick={() => setIsOpen(!isOpen)}
    >
      Show popover
    </EuiButton>`,
  },
  children: {
    type: PropTypes.ReactNode,
    value: `<div style={{ width: "300px" }}>
    Popover content that’s wider than the default
    width
  </div>`,
  },
};

```

This is the minimal configuration after removing all non-affecting factors

**Comment by anishagg17** [comment]
You can observe the [code](https://github.com/anishagg17/react-view-demo/blob/popover/src/Popover.js)  and the [demo](https://react-view-demo-git-popover.anish1712.now.sh/) for more clarifications.

**Comment by anishagg17** [comment]
@tajo is the way I am doing things not the correct one?

**Comment by tajo** [comment]
So, the problem is that there is no connection between `EuiButton`'s `onClick` and the react-view's state. When you click on it, react-view has no idea it happened and that's why the knob or source code are not updated.

Fortunately, there is a concept for this in react-view that lets you establishing this connection. We call it [state hooks](https://react-view.netlify.app/?path=/story/useview--state-hook). However, this assumes simpler scenarios where the `onClick` like handler is the top level prop. In your case, it's buried inside of the `button` prop and `EuiButton` component.

Luckily, we have one use-case like that in Base Web's [Progress Steps](https://baseweb.design/components/progress-steps/). So we built an escape hatch where you can write a custom AST visitor to correctly target and instrument the deep `onClick` handler.

So your button prop configuration should look like this:

```js
button: {
  type: PropTypes.ReactNode,
  value: `...`,
  propHook: ({getInstrumentOnChange, fnBodyAppend}) => ({
    JSXAttribute(path: any) {
      if (path.get('name').node.name === 'onClick') {
        fnBodyAppend(
          path.get('value'),
          getInstrumentOnChange('!isOpen', 'isOpen')
        );
      }
    },
  }),
},
```

This is more involved API assuming the deep knowledge of react-view. The advantage is, it can deal with pretty much anything (AST traverse is super flexible). A gist:

1. Take the `button` prop's AST and traverse it 
2. Match all `JSXAttribute` nodes
3. If the attr name is `onClick` add a secret (filtered out of the code snippet) instrumentation call that takes `!isOpen` value and updates the `isOpen` state. `getInstrumentOnChange` and `fnBodyAppend` are AST related helper functions so you don't have to write even more code.

Feel free to re-open if you have more issues.
